# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-cmake-black,
  ament-cmake-copyright,
  ament-cmake-lint-cmake,
  ament-cmake-pep257,
  ament-cmake-pytest,
  ament-cmake-python,
  ament-cmake-uncrustify,
  ament-cmake-xmllint,
  ament-lint-auto,
  ardupilot-msgs,
  builtin-interfaces,
  geographic-msgs,
  geometry-msgs,
  micro-ros-agent,
  rosgraph-msgs,
  sensor-msgs,
  std-msgs,
  tf2-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-sitl";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "dc9efdf07443d1e9a8a82689adac4933fec83848";
    sha256 = "0892r5n8wa0i7v7gs0fi9g4lq9y6wnaaq00k3c4ywx83jv43rmaq";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_sitl/";
  buildInputs = [
    ament-cmake
    ament-cmake-python
  ];
  checkInputs = [
    ament-cmake-black
    ament-cmake-copyright
    ament-cmake-lint-cmake
    ament-cmake-pep257
    ament-cmake-pytest
    ament-cmake-uncrustify
    ament-cmake-xmllint
    ament-lint-auto
  ];
  propagatedBuildInputs = [
    ardupilot-msgs
    builtin-interfaces
    geographic-msgs
    geometry-msgs
    micro-ros-agent
    rosgraph-msgs
    sensor-msgs
    std-msgs
    tf2-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python
  ];

  meta = {
    description = "ArduPlane, ArduCopter, ArduRover, ArduSub source";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
