# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-cmake-pytest,
  ament-cmake-python,
  ament-index-python,
  ament-lint-auto,
  ament-lint-common,
  ardupilot-gazebo,
  ardupilot-gz-description,
  ardupilot-gz-gazebo,
  ardupilot-sitl,
  ardupilot-sitl-models,
  launch,
  launch-ros,
  robot-state-publisher,
  ros-gz-bridge,
  ros-gz-sim,
  sdformat-urdf,
  topic-tools,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-gz-bringup";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot_gz";
    rev = "8d368dc8298d902fa5d1675d0b0d1eaf45495555";
    sha256 = "0pfqj9jmjipb3jj8fp23rlll8232wqjf0aaik8s42fakz41g9mqj";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/ardupilot_gz_bringup/";
  buildInputs = [
    ament-cmake
    ament-cmake-python
  ];
  checkInputs = [
    ament-cmake-pytest
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    ament-index-python
    ardupilot-gazebo
    ardupilot-gz-description
    ardupilot-gz-gazebo
    ardupilot-sitl
    ardupilot-sitl-models
    launch
    launch-ros
    robot-state-publisher
    ros-gz-bridge
    ros-gz-sim
    sdformat-urdf
    topic-tools
  ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python
  ];

  meta = {
    description = "Launch files for `ardupilot_gz`.";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
