# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-cmake-copyright,
  ament-cmake-cppcheck,
  ament-cmake-cpplint,
  ament-cmake-flake8,
  ament-cmake-lint-cmake,
  ament-cmake-mypy,
  ament-cmake-pclint,
  ament-cmake-pep257,
  ament-cmake-pycodestyle,
  ament-cmake-xmllint,
  ament-lint-auto,
  gz-cmake3,
  gz-common5,
  gz-plugin2,
  gz-sim8,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-gz-gazebo";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot_gz";
    rev = "8d368dc8298d902fa5d1675d0b0d1eaf45495555";
    sha256 = "0pfqj9jmjipb3jj8fp23rlll8232wqjf0aaik8s42fakz41g9mqj";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/ardupilot_gz_gazebo/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-cmake-copyright
    ament-cmake-cppcheck
    ament-cmake-cpplint
    ament-cmake-flake8
    ament-cmake-lint-cmake
    ament-cmake-mypy
    ament-cmake-pclint
    ament-cmake-pep257
    ament-cmake-pycodestyle
    ament-cmake-xmllint
    ament-lint-auto
  ];
  propagatedBuildInputs = [
    gz-cmake3
    gz-common5
    gz-plugin2
    gz-sim8
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Gazebo specific systems for `ardupilot_gz`.";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
