# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-black,
  ament-copyright,
  ament-index-python,
  ament-lint-auto,
  ament-pep257,
  ament-uncrustify,
  ament-xmllint,
  ardupilot-msgs,
  ardupilot-sitl,
  builtin-interfaces,
  geographic-msgs,
  launch,
  launch-pytest,
  launch-ros,
  micro-ros-agent,
  micro-ros-msgs,
  python3Packages,
  rclpy,
  sensor-msgs,
  socat,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-dds-tests";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "71e9765a658ce06363975eb229775e6234c6a4ac";
    sha256 = "07yq4nlkirdhizwkvisdz0jhvdhspcq62z240h2lvvy1l96jza29";
  };

  buildType = "ament_python";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_dds_tests/";
  checkInputs = [
    ament-black
    ament-copyright
    ament-lint-auto
    ament-pep257
    ament-uncrustify
    ament-xmllint
    ardupilot-msgs
    ardupilot-sitl
    launch
    launch-pytest
    launch-ros
    micro-ros-agent
    python3Packages.pytest
    python3Packages.scipy
    rclpy
    sensor-msgs
  ];
  propagatedBuildInputs = [
    ament-index-python
    ardupilot-msgs
    ardupilot-sitl
    builtin-interfaces
    geographic-msgs
    launch
    launch-pytest
    launch-ros
    micro-ros-msgs
    python3Packages.geopy
    python3Packages.pytest
    rclpy
    socat
  ];

  meta = {
    description = "Tests for the ArduPilot AP_DDS library";
    license = with lib.licenses; [ "GLP-3.0" ];
  };
}
