# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-cmake-copyright,
  ament-cmake-xmllint,
  ament-lint-auto,
  geometry-msgs,
  rosidl-default-generators,
  rosidl-default-runtime,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "71e9765a658ce06363975eb229775e6234c6a4ac";
    sha256 = "07yq4nlkirdhizwkvisdz0jhvdhspcq62z240h2lvvy1l96jza29";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_msgs/";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  checkInputs = [
    ament-cmake-copyright
    ament-cmake-xmllint
    ament-lint-auto
  ];
  propagatedBuildInputs = [
    geometry-msgs
    rosidl-default-runtime
    std-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "Custom ROS 2 messages and services for ArduPilot";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
