# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-cmake-gtest,
  ament-lint-auto,
  ament-lint-common,
  builtin-interfaces,
  micro-ros-msgs,
  rcutils,
  rmw,
  rmw-dds-common,
  rmw-fastrtps-shared-cpp,
  rosidl-default-generators,
  rosidl-typesupport-fastrtps-cpp,
}:
buildRosPackage rec {
  pname = "ros-jazzy-micro-ros-agent";
  version = "5.0.2";

  src = fetchFromGitHub {
    owner = "micro-ROS";
    repo = "micro-ROS-Agent";
    rev = "52abdf5a9897637b2539cb1c239e1ec4fa92e01c";
    sha256 = "1rxpqcc4rbnmccibs1fmjz97d8v6vs4mg3wgcly1fzz4g6gxis6f";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/micro_ros_agent/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-cmake-gtest
    ament-lint-auto
    ament-lint-common
    builtin-interfaces
    rosidl-default-generators
    rosidl-typesupport-fastrtps-cpp
  ];
  propagatedBuildInputs = [
    micro-ros-msgs
    rcutils
    rmw
    rmw-dds-common
    rmw-fastrtps-shared-cpp
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "micro-ROS Agent package";
    license = with lib.licenses; [ asl20 ];
  };
}
