# Automatically generated by: ros2nix --distro jazzy --fetch --nixfmt --no-shell --output-as-nix-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-cmake-gtest,
  ament-lint-auto,
  ament-lint-common,
  builtin-interfaces,
  micro-ros-msgs,
  rcutils,
  rmw,
  rmw-dds-common,
  rmw-fastrtps-shared-cpp,
  rosidl-default-generators,
  rosidl-typesupport-fastrtps-cpp,
}:
buildRosPackage rec {
  pname = "ros-jazzy-micro-ros-agent";
  version = "5.0.2";

  src = fetchFromGitHub {
    owner = "micro-ROS";
    repo = "micro-ROS-Agent";
    rev = "b9164d08a904580a17c1f22fd46ced977c60e1d7";
    sha256 = "18bv1v5w2bkfa9krr4jsa5is9xmhqlsyg1vqsihk88179gjsrwjf";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/micro_ros_agent/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-cmake-gtest
    ament-lint-auto
    ament-lint-common
    builtin-interfaces
    rosidl-default-generators
    rosidl-typesupport-fastrtps-cpp
  ];
  propagatedBuildInputs = [
    micro-ros-msgs
    rcutils
    rmw
    rmw-dds-common
    rmw-fastrtps-shared-cpp
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "micro-ROS Agent package";
    license = with lib.licenses; [ asl20 ];
  };
}
