# Automatically generated by: ros2nix
{
  nix-ros-overlay ? builtins.fetchTarball "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz",
  pkgs ? import nix-ros-overlay { },
  rosDistro ? "rolling",
  extraPkgs ? { },
  extraPaths ? [ ],
  withPackages ? _: [ ],
  extraShellHook ? "",
}:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths =
        [
          pkgs.colcon
          pkgs.rosPackages.${rosDistro}.ros-core

          # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
          pkgs.rosPackages.${rosDistro}.ament-cmake-core
          pkgs.rosPackages.${rosDistro}.python-cmake-module
        ]
        ++ (
          with pkgs;
          with pkgs.rosPackages.${rosDistro};
          with extraPkgs;
          [
            # Dependencies from package.xml files
            ament-black
            ament-cmake
            ament-cmake-black
            ament-cmake-copyright
            ament-cmake-gtest
            ament-cmake-lint-cmake
            ament-cmake-pep257
            ament-cmake-pytest
            ament-cmake-python
            ament-cmake-uncrustify
            ament-cmake-xmllint
            ament-copyright
            ament-index-python
            ament-lint-auto
            ament-lint-common
            ament-pep257
            ament-uncrustify
            ament-xmllint
            builtin-interfaces
            geographic-msgs
            geometry-msgs
            launch
            launch-pytest
            launch-ros
            micro-ros-msgs
            python3Packages.geopy
            python3Packages.pytest
            python3Packages.scipy
            rclpy
            rcutils
            rmw
            rmw-dds-common
            rmw-fastrtps-shared-cpp
            rosgraph-msgs
            rosidl-default-generators
            rosidl-default-runtime
            rosidl-typesupport-fastrtps-cpp
            sensor-msgs
            socat
            std-msgs
            tf2-msgs
          ]
        )
        ++ builtins.attrValues extraPkgs
        ++ extraPaths
        ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
      }
    )
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  '' + extraShellHook;
}
