# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
{ lib, buildRosPackage, fetchFromGitHub, ament-black, ament-copyright, ament-index-python, ament-lint-auto, ament-pep257, ament-uncrustify, ament-xmllint, ardupilot-msgs, ardupilot-sitl, builtin-interfaces, geographic-msgs, launch, launch-pytest, launch-ros, micro-ros-agent, micro-ros-msgs, python3Packages, pythonPackages, rclpy, sensor-msgs, socat }:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-dds-tests";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "eb4224b818fa7a8c0fbd241d11c7aa6d95f414ca";
    sha256 = "00x4bnqhqprz5wyq4j38v3vkfmsm8s2yab5arikvpzfdn4jyy7w3";
  };

  buildType = "ament_python";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_dds_tests/";
  checkInputs = [ ament-black ament-copyright ament-lint-auto ament-pep257 ament-uncrustify ament-xmllint ardupilot-msgs ardupilot-sitl launch launch-pytest launch-ros micro-ros-agent python3Packages.scipy pythonPackages.pytest rclpy sensor-msgs ];
  propagatedBuildInputs = [ ament-index-python ardupilot-msgs ardupilot-sitl builtin-interfaces geographic-msgs launch launch-pytest launch-ros micro-ros-msgs python3Packages.geopy pythonPackages.pytest rclpy socat ];

  meta = {
    description = "Tests for the ArduPilot AP_DDS library";
    license = with lib.licenses; [ "GLP-3.0" ];
  };
}
