# Automatically generated by: ros2nix --fetch --nixfmt --no-overlay --no-shell --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchgit,
  ament-cmake,
  ament-lint-auto,
  ardupilot-gazebo,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-sitl-models";
  version = "0.0.0";

  src = fetchgit {
    url = "git@github.com:teamoars/ardupilot-ros-nix.git";
    rev = "b12a1f03a63f15a78b5409b923c851275fdec4e0";
    sha256 = "0xljnw2nbn1aci7r23w3wfj8m4ahgxsjkm94ap8rw5n6m95n3r06";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/install/ardupilot_sitl_models/share/ardupilot_sitl_models/";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ];
  propagatedBuildInputs = [ ardupilot-gazebo ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Gazebo models configured for ArduPilot SITL";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
