# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-gtest, ament-lint-auto, ament-lint-common, builtin-interfaces, micro-ros-msgs, rcutils, rmw, rmw-dds-common, rmw-fastrtps-shared-cpp, rosidl-default-generators, rosidl-typesupport-fastrtps-cpp, micro-xrce-dds-agent }:
buildRosPackage rec {
  pname = "ros-jazzy-micro-ros-agent";
  version = "5.0.2";

  src = fetchFromGitHub {
    owner = "micro-ROS";
    repo = "micro-ROS-Agent";
    rev = "af007872b034d1ed31de4815377031350ab0034b";
    sha256 = "sha256-ZMRTTcvUYr1VNFxVEqoOX9JxesjTd5gEhsaN0lT7O9s=";
  };

  cmakeFlags = [
    # use local versions of everything
    "-DMICROROSAGENT_SUPERBUILD=OFF"
    "-DUAGENT_USE_SYSTEM_LOGGER=ON"
  ];

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/micro_ros_agent/";
  buildInputs = [ ament-cmake micro-xrce-dds-agent ament-lint-auto ];
  checkInputs = [ ament-cmake-gtest ament-lint-auto ament-lint-common builtin-interfaces rosidl-default-generators rosidl-typesupport-fastrtps-cpp ];
  propagatedBuildInputs = [ micro-ros-msgs rcutils rmw rmw-dds-common rmw-fastrtps-shared-cpp ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "micro-ROS Agent package";
    license = with lib.licenses; [ asl20 ];
  };
}
