# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
#
# some useful resources:
# https://github.com/ArduPilot/ardupilot/blob/master/Tools/environment_install/install-prereqs-ubuntu.sh
# https://github.com/tpwrules/ardupilot-dev-flake
{
lib,
buildRosPackage,
fetchFromGitHub,
ament-cmake,
ament-cmake-black,
ament-cmake-copyright,
ament-cmake-lint-cmake,
ament-cmake-pep257,
ament-cmake-pytest,
ament-cmake-python,
ament-cmake-uncrustify,
ament-cmake-xmllint,
ament-lint-auto,
ardupilot-msgs,
builtin-interfaces,
geographic-msgs,
geometry-msgs,
micro-ros-agent,
rosgraph-msgs,
sensor-msgs,
std-msgs,
tf2-msgs,
writers,
callPackage,
python3,
micro-xrce-dds-gen,
python3Packages,
}:
buildRosPackage rec {
  name = "ros-jazzy-ardupilot-sitl";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "f622ede25011074ba4397f97c6b3207eeb8f39cb";
    hash = "sha256-4p1uJShMVLwxzVyeYjVI+1H3jrl2JKk5mONt5QHi7+Q=";
    fetchSubmodules = true;
  };

  # stdenv = gcc13Stdenv;

  # ardupilot wants to run 'git rev-parse' but that is not possible
  # TODO: can't we get away with a simple patch instead?
  fake-git = (callPackage ./fake-git.nix { }) src;

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_sitl/";
  buildInputs = [
    ament-cmake
    ament-cmake-python
  ];

  checkInputs = [
    ament-cmake-black
    ament-cmake-copyright
    ament-cmake-lint-cmake
    ament-cmake-pep257
    ament-cmake-pytest
    ament-cmake-uncrustify
    ament-cmake-xmllint
    ament-lint-auto
  ];


  propagatedBuildInputs = [
    # this package builds ardupilot-msgs a second time instead of using the
    # provided ardupilot-msgs.. In the first place it's somewhat questionable to
    # package the sitl as a nix package so I'm not surprised this doesn't work
    # either
    ardupilot-msgs

    builtin-interfaces
    geographic-msgs
    geometry-msgs
    micro-ros-agent
    rosgraph-msgs
    sensor-msgs
    std-msgs
    tf2-msgs
  ];
  # nativeBuildInputs = [ ament-cmake ament-cmake-python breakpointHook ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python

    fake-git
    python3
    micro-xrce-dds-gen
    python3Packages.pexpect
  ];

  # setting sourceRoot makes only sourceRoot writable but the ardupilot build
  # process expects to have the whole source directory writable. To be frank I'm
  # not sure if it's the build itself or just the shebang patching.
  #
  # I previously tried to chmod in preBuild but that gives permission denied
  # errors. Is chmod explictly allowed in postUnpack or does
  # "dontMakeSourcesWritable" allow us to chmod?
  #
  # https://discourse.nixos.org/t/unpack-phase-permission-denied/13382/4
  dotMakeSourcesWritable = true;
  postUnpack = ''
    chmod -R +w /build/source
  '';

  postPatch = ''
    # silly patch bc otherwise compiler rejects isn't happy
    substituteInPlace /build/source/libraries/AP_Scripting/generator/src/main.c \
      --replace-fail 'char *var_type_name;' 'char *var_type_name = NULL;'

    patchShebangs /build/source/waf # why so long?
  '';

  meta = {
    description = "ArduPlane, ArduCopter, ArduRover, ArduSub source";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
