# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-black, ament-cmake-copyright, ament-cmake-lint-cmake, ament-cmake-pep257, ament-cmake-pytest, ament-cmake-python, ament-cmake-uncrustify, ament-cmake-xmllint, ament-lint-auto, ardupilot-msgs, builtin-interfaces, geographic-msgs, geometry-msgs, micro-ros-agent, rosgraph-msgs, sensor-msgs, std-msgs, tf2-msgs, python311, writers, callPackage, waf }:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-sitl";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "eb4224b818fa7a8c0fbd241d11c7aa6d95f414ca";
    hash = "sha256-gx/vJbHN/btnzKos5YVGVVc399hoSII9Lz9fDLFdpAM=";
    # fetchSubmodules = true;
  };

  # ardupilot wants to run 'git rev-parse' but that is not possible
  fake-git = (callPackage ./fake-git.nix { }) src;

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_sitl/";
  buildInputs = [ ament-cmake ament-cmake-python fake-git waf ];
  checkInputs = [ ament-cmake-black ament-cmake-copyright ament-cmake-lint-cmake ament-cmake-pep257 ament-cmake-pytest ament-cmake-uncrustify ament-cmake-xmllint ament-lint-auto ];
  propagatedBuildInputs = [ ardupilot-msgs builtin-interfaces geographic-msgs geometry-msgs micro-ros-agent rosgraph-msgs sensor-msgs std-msgs tf2-msgs ];
  nativeBuildInputs = [ ament-cmake ament-cmake-python ];

  meta = {
    description = "ArduPlane, ArduCopter, ArduRover, ArduSub source";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
