# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
# most of the info is in https://github.com/ArduPilot/ardupilot/blob/master/Tools/environment_install/install-prereqs-ubuntu.sh
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-black, ament-cmake-copyright, ament-cmake-lint-cmake, ament-cmake-pep257, ament-cmake-pytest, ament-cmake-python, ament-cmake-uncrustify, ament-cmake-xmllint, ament-lint-auto, ardupilot-msgs, builtin-interfaces, geographic-msgs, geometry-msgs, micro-ros-agent, rosgraph-msgs, sensor-msgs, std-msgs, tf2-msgs, python311, writers, callPackage, python3, micro-xrce-dds-gen, python3Packages, breakpointHook, fetchPypi }:
let
  empy' = python3Packages.empy.overridePythonAttrs(old: rec {
    version = "3.3.4";
    src =  fetchPypi {
      pname = "empy";
      inherit version;
      sha256 = "sha256-c6xJeFtgFHnfTqGKfHm8EwSop8NMArlHLPEgauiPAbM=";
    };
  });
in
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-sitl";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "f622ede25011074ba4397f97c6b3207eeb8f39cb";
    hash = "sha256-4p1uJShMVLwxzVyeYjVI+1H3jrl2JKk5mONt5QHi7+Q=";
    fetchSubmodules = true;
  };

  # ardupilot wants to run 'git rev-parse' but that is not possible
  # TODO: can't we get away with a simple patch instead?
  fake-git = (callPackage ./fake-git.nix { }) src;

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_sitl/";
  buildInputs = [
    ament-cmake
    ament-cmake-python
  ];

  checkInputs = [
    ament-cmake-black
    ament-cmake-copyright
    ament-cmake-lint-cmake
    ament-cmake-pep257
    ament-cmake-pytest
    ament-cmake-uncrustify
    ament-cmake-xmllint
    ament-lint-auto
  ];


  propagatedBuildInputs = [
    ardupilot-msgs
    builtin-interfaces
    geographic-msgs
    geometry-msgs
    micro-ros-agent
    rosgraph-msgs
    sensor-msgs
    std-msgs
    tf2-msgs
  ];
  # nativeBuildInputs = [ ament-cmake ament-cmake-python breakpointHook ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python

    fake-git
    python3
    micro-xrce-dds-gen
    python3Packages.pexpect
    python3Packages.setuptools
    python3Packages.future
    python3Packages.intelhex
    python3Packages.scipy
    empy'
  ];

  # setting sourceRoot makes only sourceRoot writable but the ardupilot build
  # process expects to have the whole source directory writable. To be frank I'm
  # not sure if it's the build itself or just the shebang patching.
  #
  # I previously tried to chmod in preBuild but that gives permission denied
  # errors. Is chmod explictly allowed in postUnpack or does
  # "dontMakeSourcesWritable" allow us to chmod?
  #
  # https://discourse.nixos.org/t/unpack-phase-permission-denied/13382/4
  dontMakeSourcesWritable = true;
  postUnpack = ''
    chmod -R +w ${src.name}
  '';

  # waf has "/usr/bin/env python3"
  preBuild = ''
    patchShebangs /build/source/waf # why so long?
  '';

  meta = {
    description = "ArduPlane, ArduCopter, ArduRover, ArduSub source";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
