# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-copyright, ament-cmake-xmllint, ament-lint-auto, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, std-msgs }:
buildRosPackage rec {
  name = "ros-jazzy-ardupilot-msgs";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "f622ede25011074ba4397f97c6b3207eeb8f39cb";
    hash = "sha256-G0YaYzzdHzWRhjWutHHbt+XIZPvcLlnNeMy4HXXDBeI=";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_msgs/";
  buildInputs = [ ament-cmake rosidl-default-generators ];
  checkInputs = [ ament-cmake-copyright ament-cmake-xmllint ament-lint-auto ];
  propagatedBuildInputs = [ geometry-msgs rosidl-default-runtime std-msgs ];
  nativeBuildInputs = [ ament-cmake rosidl-default-generators ];

  meta = {
    description = "Custom ROS 2 messages and services for ArduPilot";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
