# Automatically generated by: ros2nix --output-as-nix-pkg-name --fetch --distro jazzy --flake
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-cmake-copyright, ament-cmake-xmllint, ament-lint-auto, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, std-msgs }:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot";
    rev = "eb4224b818fa7a8c0fbd241d11c7aa6d95f414ca";
    sha256 = "00x4bnqhqprz5wyq4j38v3vkfmsm8s2yab5arikvpzfdn4jyy7w3";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/Tools/ros2/ardupilot_msgs/";
  buildInputs = [ ament-cmake rosidl-default-generators ];
  checkInputs = [ ament-cmake-copyright ament-cmake-xmllint ament-lint-auto ];
  propagatedBuildInputs = [ geometry-msgs rosidl-default-runtime std-msgs ];
  nativeBuildInputs = [ ament-cmake rosidl-default-generators ];

  meta = {
    description = "Custom ROS 2 messages and services for ArduPilot";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
