# Automatically generated by: ros2nix --fetch --nixfmt --no-overlay --no-shell --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchgit,
  ament-cmake,
  ament-cmake-copyright,
  ament-cmake-cppcheck,
  ament-cmake-cpplint,
  ament-cmake-flake8,
  ament-cmake-lint-cmake,
  ament-cmake-mypy,
  ament-cmake-pclint,
  ament-cmake-pep257,
  ament-cmake-pycodestyle,
  ament-cmake-xmllint,
  ament-lint-auto,
  gz-cmake3,
  gz-common5,
  gz-plugin2,
  gz-sim8,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-gz-gazebo";
  version = "0.0.0";

  src = fetchgit {
    url = "git@github.com:teamoars/ardupilot-ros-nix.git";
    rev = "b12a1f03a63f15a78b5409b923c851275fdec4e0";
    sha256 = "0xljnw2nbn1aci7r23w3wfj8m4ahgxsjkm94ap8rw5n6m95n3r06";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/install/ardupilot_gz_gazebo/share/ardupilot_gz_gazebo/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-cmake-copyright
    ament-cmake-cppcheck
    ament-cmake-cpplint
    ament-cmake-flake8
    ament-cmake-lint-cmake
    ament-cmake-mypy
    ament-cmake-pclint
    ament-cmake-pep257
    ament-cmake-pycodestyle
    ament-cmake-xmllint
    ament-lint-auto
  ];
  propagatedBuildInputs = [
    gz-cmake3
    gz-common5
    gz-plugin2
    gz-sim8
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Gazebo specific systems for `ardupilot_gz`.";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
