# Automatically generated by: ros2nix --fetch --nixfmt --no-overlay --no-shell --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-gz-application";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "ArduPilot";
    repo = "ardupilot_gz";
    rev = "8d368dc8298d902fa5d1675d0b0d1eaf45495555";
    sha256 = "0pfqj9jmjipb3jj8fp23rlll8232wqjf0aaik8s42fakz41g9mqj";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/ardupilot_gz_application/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Application code for `ardupilot_gz`.";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
