# Automatically generated by: ros2nix --fetch --nixfmt --no-overlay --no-shell --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchgit,
  ament-cmake,
  ament-lint-auto,
  gst_all_1,
  gz-cmake3,
  gz-sim8,
  opencv,
  rapidjson,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-gazebo";
  version = "0.0.0";

  src = fetchgit {
    url = "git@github.com:teamoars/ardupilot-ros-nix.git";
    rev = "b12a1f03a63f15a78b5409b923c851275fdec4e0";
    sha256 = "0xljnw2nbn1aci7r23w3wfj8m4ahgxsjkm94ap8rw5n6m95n3r06";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/install/ardupilot_gazebo/share/ardupilot_gazebo/";
  buildInputs = [
    ament-cmake
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-base
    gst_all_1.gstreamer
    opencv
    opencv.cxxdev
    rapidjson
  ];
  checkInputs = [ ament-lint-auto ];
  propagatedBuildInputs = [
    gz-cmake3
    gz-sim8
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Plugins and models for vehicle simulation in Gazebo Sim with ArduPilot SITL controllers";
    license = with lib.licenses; [ "LGPL-3.0" ];
  };
}
