# Automatically generated by: ros2nix --fetch --nixfmt --no-overlay --no-shell --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchgit,
  ament-cmake,
  ament-cmake-pytest,
  ament-cmake-python,
  ament-index-python,
  ament-lint-auto,
  ament-lint-common,
  ardupilot-gazebo,
  ardupilot-gz-description,
  ardupilot-gz-gazebo,
  ardupilot-sitl,
  ardupilot-sitl-models,
  launch,
  launch-ros,
  robot-state-publisher,
  ros-gz-bridge,
  ros-gz-sim,
  sdformat-urdf,
  topic-tools,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ardupilot-gz-bringup";
  version = "0.0.0";

  src = fetchgit {
    url = "git@github.com:teamoars/ardupilot-ros-nix.git";
    rev = "b12a1f03a63f15a78b5409b923c851275fdec4e0";
    sha256 = "0xljnw2nbn1aci7r23w3wfj8m4ahgxsjkm94ap8rw5n6m95n3r06";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/install/ardupilot_gz_bringup/share/ardupilot_gz_bringup/";
  buildInputs = [
    ament-cmake
    ament-cmake-python
  ];
  checkInputs = [
    ament-cmake-pytest
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    ament-index-python
    ardupilot-gazebo
    ardupilot-gz-description
    ardupilot-gz-gazebo
    ardupilot-sitl
    ardupilot-sitl-models
    launch
    launch-ros
    robot-state-publisher
    ros-gz-bridge
    ros-gz-sim
    sdformat-urdf
    topic-tools
  ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python
  ];

  meta = {
    description = "Launch files for `ardupilot_gz`.";
    license = with lib.licenses; [ "GPL-3.0" ];
  };
}
